# -*- coding: utf-8 -*-
"""_Kmeans_scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LbVsqnEdz1IG6qdS504ykr1_f9Dsu8Z
"""

import numpy as np

class KMeans_Clustering:
    def __init__(self, n_clusters=2, max_iter=100, random_state=None):
        self.n_clusters = n_clusters
        self.max_iter = max_iter
        self.random_state = random_state
        if self.random_state:
            np.random.seed(self.random_state)
        self.centroids = None
        self.labels = None

    def fit(self, X):
        # Initialize centroids randomly from the data points
        idx = np.random.choice(X.shape[0], self.n_clusters, replace=False)
        self.centroids = X[idx]

        for _ in range(self.max_iter):
            # Assign each data point to the closest centroid
            self.labels = self._assign_clusters(X)

            # Update centroids based on the mean of assigned points
            new_centroids = self._update_centroids(X)

            # Check for convergence
            if np.allclose(self.centroids, new_centroids):
                break
            self.centroids = new_centroids

    def _assign_clusters(self, X):
        distances = np.array([np.linalg.norm(X - centroid, axis=1) for centroid in self.centroids])
        return np.argmin(distances, axis=0)

    def _update_centroids(self, X):
        new_centroids = np.zeros_like(self.centroids)
        for i in range(self.n_clusters):
            points_in_cluster = X[self.labels == i]
            if len(points_in_cluster) > 0:
                new_centroids[i] = np.mean(points_in_cluster, axis=0)
            # else: centroid remains unchanged if no points are assigned to it
        return new_centroids

    def predict(self, X):
        # For K-Means, predict typically means assigning clusters, not classification labels directly.
        # If used for classification, one would typically map clusters to majority labels post-training.
        # This implementation returns cluster assignments.
        if self.centroids is None:
            raise RuntimeError("KMeans must be fitted before predicting.")
        return self._assign_clusters(X)