# -*- coding: utf-8 -*-
"""Gaussian_Naive_Bayes_Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMk8paNPP8gWksyHsaKoJP7nnx1yZRwJ
"""

import numpy as np

class NaiveBayesClassifier:

    def fit(self, X_train, y_train):
        self.classes = np.unique(y_train)
        self.mean = {}
        self.var = {}
        self.prior = {}

        for c in self.classes:
            Xc = X_train[y_train == c]
            self.mean[c] = Xc.mean(axis=0)
            self.var[c] = Xc.var(axis=0) + 1e-6
            self.prior[c] = len(Xc) / len(X_train)

    def gaussian(self, x, mean, var):
        numerator = np.exp(-(x - mean) ** 2 / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator

    def predict_one(self, x):
        posteriors = {}

        for c in self.classes:
            likelihood = np.prod(self.gaussian(x, self.mean[c], self.var[c]))
            posteriors[c] = likelihood * self.prior[c]

        return max(posteriors, key=posteriors.get)

    def predict(self, X_test):
        return np.array([self.predict_one(x) for x in X_test])