# -*- coding: utf-8 -*-
"""Hypersphere_Classifier_Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMk8paNPP8gWksyHsaKoJP7nnx1yZRwJ
"""

import numpy as np
import math

class HypersphereClassifier:

    def fit(self, X_train, y_train):
        self.classes = np.unique(y_train)
        self.centers = {}
        self.radius = {}

        for c in self.classes:
            Xc = X_train[y_train == c]
            center = Xc.mean(axis=0)
            self.centers[c] = center

            distances = [math.dist(x, center) for x in Xc]
            self.radius[c] = max(distances)

    def predict_one(self, x):
        scores = {}

        for c in self.classes:
            d = math.dist(x, self.centers[c])
            scores[c] = d / (self.radius[c] + 1e-6)

        return min(scores, key=scores.get)

    def predict(self, X_test):
        return np.array([self.predict_one(x) for x in X_test])